/**
 * Crafting and Smelting Tuning Configuration
 */
module.exports = {
  CRAFTING_TABLE_SEARCH_RADIUS: 24,
  FURNACE_SEARCH_RADIUS: 24,
  MAX_RECURSIVE_CRAFT_DEPTH: 6,
  SMELT_POLL_INTERVAL_MS: 1000,
  MAX_SMELT_WAIT_MS: 60000,
  TABLE_INTERACTION_RANGE: 3.5,
  AUTO_RETRIEVE_PLACED_TABLE: true
};
