/**
 * Forestry Data - Static Definitions for Tree Species, Blocks, Saplings, and Substrates.
 * Pure data — no Mineflayer calls and no logic.
 */
module.exports = {
  families: {
    oak: {
      logBlocks: ['oak_log'],
      strippedLogBlocks: ['stripped_oak_log'],
      leafBlocks: ['oak_leaves'],
      saplingItem: 'oak_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      maxSafeHeight: 32,
      dimension: 'overworld',
    },
    birch: {
      logBlocks: ['birch_log'],
      strippedLogBlocks: ['stripped_birch_log'],
      leafBlocks: ['birch_leaves'],
      saplingItem: 'birch_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      maxSafeHeight: 32,
      dimension: 'overworld',
    },
    spruce: {
      logBlocks: ['spruce_log'],
      strippedLogBlocks: ['stripped_spruce_log'],
      leafBlocks: ['spruce_leaves'],
      saplingItem: 'spruce_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      maxSafeHeight: 48,
      dimension: 'overworld',
    },
    jungle: {
      logBlocks: ['jungle_log'],
      strippedLogBlocks: ['stripped_jungle_log'],
      leafBlocks: ['jungle_leaves'],
      saplingItem: 'jungle_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      maxSafeHeight: 64,
      dimension: 'overworld',
    },
    acacia: {
      logBlocks: ['acacia_log'],
      strippedLogBlocks: ['stripped_acacia_log'],
      leafBlocks: ['acacia_leaves'],
      saplingItem: 'acacia_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      maxSafeHeight: 32,
      dimension: 'overworld',
    },
    dark_oak: {
      logBlocks: ['dark_oak_log'],
      strippedLogBlocks: ['stripped_dark_oak_log'],
      leafBlocks: ['dark_oak_leaves'],
      saplingItem: 'dark_oak_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      requiresSaplings: 4,
      maxSafeHeight: 32,
      dimension: 'overworld',
    },
    mangrove: {
      logBlocks: ['mangrove_log'],
      strippedLogBlocks: ['stripped_mangrove_log'],
      leafBlocks: ['mangrove_leaves'],
      saplingItem: 'mangrove_propagule',
      plantableGround: ['mud', 'dirt', 'grass_block', 'rooted_dirt'],
      maxSafeHeight: 40,
      dimension: 'overworld',
    },
    cherry: {
      logBlocks: ['cherry_log'],
      strippedLogBlocks: ['stripped_cherry_log'],
      leafBlocks: ['cherry_leaves'],
      saplingItem: 'cherry_sapling',
      plantableGround: ['dirt', 'grass_block', 'podzol', 'coarse_dirt'],
      maxSafeHeight: 32,
      dimension: 'overworld',
    },
    crimson: {
      logBlocks: ['crimson_stem'],
      strippedLogBlocks: ['stripped_crimson_stem'],
      leafBlocks: ['nether_wart_block', 'shroomlight'],
      saplingItem: 'crimson_fungus',
      plantableGround: ['crimson_nylium'],
      maxSafeHeight: 40,
      dimension: 'nether',
    },
    warped: {
      logBlocks: ['warped_stem'],
      strippedLogBlocks: ['stripped_warped_stem'],
      leafBlocks: ['warped_wart_block', 'shroomlight'],
      saplingItem: 'warped_fungus',
      plantableGround: ['warped_nylium'],
      maxSafeHeight: 40,
      dimension: 'nether',
    },
  },

  aliases: {
    wood: 'any',
    logs: 'any',
    log: 'any',
    tree: 'any',
    trees: 'any',
    oakwood: 'oak',
    darkoak: 'dark_oak',
    dark_oak: 'dark_oak',
    netherwood: 'any_nether',
    nether: 'any_nether',
  },

  defaults: {
    targetFamily: 'any',
    quantity: 64,
    searchRadius: 48,
    replant: true,
    collectSaplings: true,
    collectApples: true,
  },
};
