/**
 * Forestry and Woodcutting Skill Configuration Tuning Values
 */
module.exports = {
  DEFAULT_SEARCH_RADIUS: 48,
  MAX_SEARCH_RADIUS: 96,
  TREE_SCAN_VERTICAL_RANGE: 64,
  MAX_LOGS_PER_TREE: 160,
  MAX_TREE_HEIGHT_OVERWORLD: 64,
  MAX_TREE_HEIGHT_NETHER: 64,
  MIN_SAPLING_RESERVE: 8,
  INVENTORY_FULL_RATIO: 0.90,
  DROP_COLLECTION_RADIUS: 8,
  SAFE_TREE_DISTANCE_FROM_BASE: 12,
  MAX_UNREACHABLE_TREES_BEFORE_STOP: 3,
  TREE_RESCAN_DELAY_MS: 1000,
  LEAF_DECAY_WAIT_MS: 3000,
  PROGRESS_EMIT_EVERY_LOGS: 8,
  CHECKPOINT_EVERY_LOGS: 32,
  DEFAULT_TASK_TIMEOUT_MS: 15 * 60 * 1000,
};
